### ISSUE TITLE
Error using with atom

### ISSUE THREAD

**Issue by timrichd** [cvazac/eslint-plugin-react-perf#3]
my `.eslintrc`:
```
{ "extends": "eslint-config-airbnb",
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "react/no-multi-comp": 0,
    "import/default": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-unresolved": 0,
    "import/no-named-as-default": 2,
    "comma-dangle": 0,  // not sure why airbnb turned this on. gross!
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-console": 0,
    "no-alert": 0,
    "no-unused-vars": 1, // set to warning instead of error (better for development)
    "id-length": [3, {"min": 2, "properties": "never", "exceptions": ["t", "_", "i", "j", "k"]}], // allow underscore
    "react-perf/jsx-no-new-object-as-prop": 1,
    "react-perf/jsx-no-new-array-as-prop": 1,
    "react-perf/jsx-no-new-function-as-prop": 1,
    "react-perf/jsx-no-jsx-as-prop": 1,
  },
  "plugins": [
    "react", "import", "react-perf",
  ],
  "settings": {
    "import/parser": "babel-eslint",
    "import/resolve": {
      "moduleDirectory": ["node_modules", "src"]
    },
  },
  "globals": {
    "__DEVELOPMENT__": true,
    "__CLIENT__": true,
    "__SERVER__": true,
    "__DISABLE_SSR__": true,
    "__DEVTOOLS__": true,
    "__API_PATH__": true,
    "webpackIsomorphicTools": true
  }
}
```
Atom throws the following error:
```
Error: Error while loading rule 'react-perf/jsx-no-new-object-as-prop': ruleCreator is not a function

TypeError: Error while loading rule 'react-perf/jsx-no-new-object-as-prop': ruleCreator is not a function
    at /home/tim/workspace/projects/sapientia-web/src/app/node_modules/eslint/lib/eslint.js:692:28
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/home/tim/workspace/projects/sapientia-web/src/app/node_modules/eslint/lib/eslint.js:671:16)
    at processText (/home/tim/workspace/projects/sapientia-web/src/app/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/home/tim/workspace/projects/sapientia-web/src/app/node_modules/eslint/lib/cli-engine.js:686:26)
    at Object.execute (/home/tim/workspace/projects/sapientia-web/src/app/node_modules/eslint/lib/cli.js:162:36)
    at lintJob (/home/tim/.atom/packages/linter-eslint/lib/worker.js:38:10)
    at /home/tim/.atom/packages/linter-eslint/lib/worker.js:75:20
    at Emitter.emit (/home/tim/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/tim/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:22:23
```

**Comment by cvazac** [comment]
atom integration works for me, my setup:
atom: 1.13.0, linter: 1.11.21, linter-eslint: 8.0.0, node: 7.2.0, estlint: 3.8.1, eslint-plugin-react-perf: 2.0.4

does `eslint` work from command line?
one thing to check: i believe `eslint` and `eslint-plugin-react-perf` need to be either both locally _or_ both globally installed
<img width="732" alt="screen shot 2017-01-13 at 1 15 08 pm" src="https://cloud.githubusercontent.com/assets/9857665/21945841/6148154c-d992-11e6-9800-49ee8cc40742.png">
